App\Bundle\MainBundle\Entity\Account:
    type: entity
    table: account
    repositoryClass: App\Bundle\MainBundle\Entity\AccountRepository
    id:
        identifier:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
            unique: true
        credentials:
            type: string
            length: 255
        domain:
            type: string
            length: 255
