<?php

namespace App\Bundle\MainBundle\Entity;

/**
 * The doctrine entity representing an account
 */
class Account
{
    /**
     * The unique identifier generated by doctrine
     *
     * @var int
     */
    private $identifier;

    /**
     * The username for this account
     *
     * @var string
     */
    private $username;

    /**
     * The credentials for this account
     *
     * @var string
     */
    private $credentials;

    /**
     * The domain where this account is stored
     *
     * @var string
     */
    private $domain;

    /**
     * Get identifier
     *
     * @return int
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set username
     *
     * @param string $username
     *
     * @return Account
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get credentials
     *
     * @return string
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    /**
     * Set credentials
     *
     * @param string $credentials
     *
     * @return Account
     */
    public function setCredentials($credentials)
    {
        $this->credentials = $credentials;

        return $this;
    }

    /**
     * Get domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Set domain
     *
     * @param string $domain
     *
     * @return Account
     */
    public function setDomain($domain)
    {
        $this->domain = $domain;

        return $this;
    }
}
